import 'package:flutter/material.dart';

/// The opt-in a rewarded ad requires: the user is told what they get and
/// chooses. Returns true when they agreed to watch.
///
/// A separate file from the gate's decision logic (`rewarded_describe_gate`)
/// because this half needs a `BuildContext` and that half must stay testable
/// without one.
///
/// The copy names the exchange plainly and does NOT dress the ad up as a
/// feature. It also avoids promising the description itself is free after the
/// ad -- the daily cap still applies, and a prompt that implies otherwise
/// would be the app's own words contradicting the counter in the sheet.
Future<bool> showRewardedDescribePrompt(BuildContext context) async {
  final agreed = await showDialog<bool>(
    context: context,
    builder: (ctx) => AlertDialog(
      title: const Text('Watch an ad to describe this?'),
      content: const Text(
        'Descriptions are generated by Google, which costs us per photo. '
        'Watch a short ad and this one is on us.\n\n'
        'Your photo is never part of the ad, and advertisers are never told '
        'anything about it.',
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(ctx, false),
          child: const Text('Not now'),
        ),
        FilledButton(
          onPressed: () => Navigator.pop(ctx, true),
          child: const Text('Watch ad'),
        ),
      ],
    ),
  );
  return agreed ?? false;
}
